default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://zavy:password@zavy-postgres:5432/zavy_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://zavy:password@zavy-postgres:5432/zavy_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
